### ISSUE TITLE
How to access rpc instance from client plugin

### ISSUE THREAD

**Issue by Nemesis-git** [rsmusllp/king-phisher#434]
Hello all ! Firstly, I'd like to say I am really enjoying your powerful tool ! 

I am currently building a new custom functionality for my needs with both a client and server plugin which communicate by custom RPC functions. And I would like to know if it's possible to access the rpc instance (which is initialized by King Phisher Client) from my client plugin ? Or do we need to have 2 rpc channels, one for KP Client - KP Server communications and one for Client Plugin - Server Plugin communications (not really convenient) ?

Thank you very much !

**Comment by zeroSteiner** [comment]
Yes you can use the existing RPC channel, and that's what I would recommend. This isn't super well supported because it isn't common. There is one example of a plugin that you can look at which does this and that's the "Request Redirect" plugin. It includes a server component which [adds new RPC methods](https://github.com/rsmusllp/king-phisher-plugins/blob/master/server/request_redirect.py#L206-L212) and a client plugin with a GUI that [uses them](https://github.com/rsmusllp/king-phisher-plugins/blob/master/client/request_redirect/__init__.py#L83-L87). Once the RPC functions have been added they can be called like any others.

Also check out sever plugin documentation for [Adding RPC Methods](https://king-phisher.readthedocs.io/en/latest/plugins/server.html#adding-rpc-methods).

Pro-tip: to ensure you're not locking the GUI while invoking RPC functions, use the async RPC functions like [`async_call`](https://king-phisher.readthedocs.io/en/latest/king_phisher/client/client_rpc.html#king_phisher.client.client_rpc.KingPhisherRPCClient.async_call).

**Comment by Nemesis-git** [comment]
Thank you for your answer and your tips, I tried it and it works pretty well ! I was mainly looking for the "**self.application.rpc**" object. 

I have a last question, is there a way to kind of whitelisting rpc users and only permit login to a predefined set of linux users ?

**Comment by zeroSteiner** [comment]
If you mean to the King Phisher server, the easiest way to do that is would be to require a group membership. Do that by setting the [`server.authentication.group`](https://github.com/rsmusllp/king-phisher/blob/master/data/server/king_phisher/server_config.yml#L44) setting in the server configuration file. If you mean within your specific plugin, you'll have to check the user on each request and evaluate it appropriately. There is also an unexposed property of users [`is_admin`](https://github.com/rsmusllp/king-phisher/blob/master/king_phisher/server/database/models.py#L521) that you could use if you wanted. By default no users are admins. Admins have to be promoted directly through the database and it just provides a looser set of security restrictions that is helpful in certain cases.

**Comment by Nemesis-git** [comment]
Yes I was meaning to the King Phisher server. I haven't noticed this setting before, it's pretty useful in order to enhance the tool's security ! 
Thank you for your answer.
