### ISSUE TITLE
KingPhisher.exe V1.15.0 requires MSVCR100.dll

### ISSUE THREAD

**Issue by mubix** [rsmusllp/king-phisher#445]
## Issue Description
KingPhisher.exe V1.15.0 requires MSVCR100.dll. (Not statically compiled)

To reproduce install KingPhisher1.15.0-win32.msi

**Comment by mubix** [comment]
Works after install of Microsoft Visual C++ 2010 Redistributable Package (x86) - https://www.microsoft.com/en-us/download/details.aspx?id=5555

**Comment by zeroSteiner** [comment]
Well this is disappointing. This issue sounds like something we could fix pretty well but the maintainers (@wolfthefallen and I) no longer have access to the build infrastructure for generating the MSI files. It's unlikely that there will be Windows builds moving forward for that reason. Additionally, the Windows libs for GObject are preventing us from updating quite a few things.

**Comment by mubix** [comment]
Thoughts on just using Github Actions to build the MSI?

**Comment by zeroSteiner** [comment]
Well that certainly would be an ideal solution. I'd need to look back through my notes to see how feasible it would be to get all of the dependencies and everything setup for an automated build. I haven't used GitHub Actions before so it won't be easy.

The other thing is to be honest I don't think it's a good use of time to fix the MSI build when again, it's holding the project back because alot of our libraries can't be upgraded. For example, IIRC we can't upgrade matplotlib because we'll lose Python 3.4 support which is required by the Windows GObject lib.

**Comment by zeroSteiner** [comment]
I'll do some research. I don't want it to seem like I'm shooting this down, it just won't be a trivial fix any more and I want to make sure I'm using my limited resources effectively. Thanks alot for bringing it to our attention.

**Comment by zeroSteiner** [comment]
I looked into it a bit and consulted the subject matter expert @wolfthefallen and we both agreed we can't continue to release Windows builds. While we could rebuild the infrastructure, and building it on top of GitHub Actions would be amazing, that wouldn't address the largest issue which is that we have no way forward without dropping Windows support due to the [PyGObject for Windows](https://sourceforge.net/projects/pygobjectwin32/files/) project being abandoned. Because that project can't be compiled for Python versions 3.5 and newer, we've been stuck pinning a number of libraries to older versions, including the apparently outdated and vulnerable [cryptography](/rsmusllp/king-phisher/pull/447) library. `cryptography` is just the next entry in a list of libraries that have dropped v3.4 support that we can't upgrade.

I'm sorry but we're not going to be able to address this.
